version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - LANGSMITH_API_KEY=your_langsmith_key_here
      - OPENROUTER_API_KEY=your_openrouter_key_here
      - TAVILY_API_KEY=your_tavily_key_here
      - CONFIG_PATH=config.yaml
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
