app:
  name: Property Analysis Agentic System
  version: 1.0.0
  default_city: Los Angeles
  response_timeout_sec: 110

agents:
  framework: crewai

integrations:
  llm:
    provider: groq
    base_url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.1-8b-instant
    fallback_models:
      - llama-3.3-70b-versatile
    temperature: 0.2
    max_tokens: 700
    request_timeout_sec: 90
                        

  search:
    provider: tavily
    base_url: https://api.tavily.com/search
    max_results: 6
    include_answer: false
    include_images: false
    request_timeout_sec: 30

report:
  sections:
    - Summary
    - Parcel & Zoning
    - Permits & History
    - Constraints & Overlays
    - Development Potential
    - Risks & Red Flags
    - Sources
